// <auto-generated />
namespace Microsoft.Extensions.DependencyInjection.Ordered
{
    using System.Globalization;
    using System.Reflection;
    using System.Resources;

    internal static class Resources
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("Microsoft.Extensions.DependencyInjection.Ordered.Resources", typeof(Resources).GetTypeInfo().Assembly);

        /// <summary>
        /// '{0}' object has been disposed.
        /// </summary>
        internal static string ObjectDisposedException
        {
            get { return GetString("ObjectDisposedException"); }
        }

        /// <summary>
        /// '{0}' object has been disposed.
        /// </summary>
        internal static string FormatObjectDisposedException(object p0)
        {
            return string.Format(CultureInfo.CurrentCulture, GetString("ObjectDisposedException"), p0);
        }

        /// <summary>
        /// Unsupported service descriptor type '{0}'
        /// </summary>
        internal static string UnsupportedServiceDescriptorType
        {
            get { return GetString("UnsupportedServiceDescriptorType"); }
        }

        /// <summary>
        /// Unsupported service descriptor type '{0}'
        /// </summary>
        internal static string FormatUnsupportedServiceDescriptorType(object p0)
        {
            return string.Format(CultureInfo.CurrentCulture, GetString("UnsupportedServiceDescriptorType"), p0);
        }

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);

            System.Diagnostics.Debug.Assert(value != null);

            if (formatterNames != null)
            {
                for (var i = 0; i < formatterNames.Length; i++)
                {
                    value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
                }
            }

            return value;
        }
    }
}
